### PR TITLE
Added ability to inject SSH key using ENV variables

### LINKED ISSUE #5: User SSH key using environment variables
Hi,

First of all, I want to say that this is a great project and helps us a lot in testing FTP.

We would like to use this project inside Continuous Integration, but the problem is that it does not allow us to mount volumes so we are not able to test things using SSH keys. One way to solve this would be introducing the ability to inject user SSH keys using environment variables. I think this could be done by establishing some sort of convention in env var names, for example, `SSH_PUBLIC_KEY_FOO` could be used to set a public SSH key for a user named `foo`. The key injected using env var would be appended to `/home/$user/.ssh/authorized_keys` so there is no conflict with the already existing method using mounts.

It would be great if you shared your view on the proposed approach and if all makes sense we would be happy to contribute with the required changes.

### PR DESCRIPTION
**Pull request by martinssipenko**
Fixes #5

### CODE REVIEW

**Comment by CybotTM** [comment]
This breaks the tests.

**Comment by martinssipenko** [comment]
Is there a way to run those tests? I could fix them.

**Comment by martinssipenko** [comment]
@CybotTM looks like tests are broken even after revert, is this change really breaking them?

**Comment by CybotTM** [comment]
The test includes username with dots, wich results in:
```
/entrypoint: line 85: SSH_PUB_KEY_user.with.dot: invalid variable name
```

**Comment by martinssipenko** [comment]
Ok I'll check if I can fix this somehow.

**Comment by CybotTM** [comment]
Hi @martinssipenko , i fixed it in https://github.com/netresearch/docker-sftp/commit/92026e2f507bc81c716e411584fecfc449e79c01

**Pull request merged**
